# render.yaml
services:

  - type: web
    name: girerep-backend 
    rootDir: server/girerep 
   
    dockerfilePath: server/girerep/Dockerfile 
    autoDeploy: true
    plan: free 
    envVars:
     
      - key: MYSQL_HOST
        value: ${mysql.host} 
      - key: MYSQL_PORT
        value: ${mysql.port}
      - key: MYSQL_USER
        value: ${mysql.user}
      - key: MYSQL_PASSWORD
        value: ${mysql.password}
      - key: MYSQL_DATABASE
        value: ${mysql.database}
      - key: HIBERNATE_DDL_AUTO
        value: update
      - key: JWT_SECRET
        value: sua_chave_secreta_jwt_render
      - key: JWT_EXPIRATION
        value: 86400000

 
  - type: web
    name: girerep-frontend 
    rootDir: web 
    buildCommand: npm install && npm run build
    startCommand: npm start
    env: node 
    autoDeploy: true
    plan: free
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://girerep-backend.onrender.com